// Generate src/version.ts with an auto-incrementing build number based on git commit count
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getCommitCount() {
  try {
    const out = execSync('git rev-list --count HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
    return parseInt(out, 10);
  } catch {
    return 0;
  }
}

function getShortSha() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'unknown';
  }
}

const count = getCommitCount();
const sha = getShortSha();
const version = `v0.0.${count}`;
const stamp = new Date().toISOString();

const out = `// This file is generated by scripts/gen_version.cjs during build\n`+
`export const APP_VERSION = '${version}';\n`+
`export const APP_COMMIT = '${sha}';\n`+
`export const BUILD_TIME = '${stamp}';\n`;

const dest = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(dest, out, 'utf8');
console.log(`Generated version: ${version} (${sha})`);

